import type { Metadata } from "next";
import { Fustat, Geist, Geist_Mono } from "next/font/google";
import { Montserrat } from "next/font/google";
import { Hanken_Grotesk } from "next/font/google";

import "./globals.css";

const fustat = Fustat({
  variable: "--font-fustat",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const hankenGrotesk = Hanken_Grotesk({
  variable: "--font-hanken-grotesk",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Sebatik Barat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} ${geistMono.variable} ${montserrat.variable}
          ${fustat.variable} ${hankenGrotesk.variable}
        `}
      >
        {/* MAIN akan mengisi ruang yang tersedia */}
        <main className="flex-grow">{children}</main>
      </body>
    </html>
  );
}
